name: Build Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Install Capacitor CLI
        run: npm install @capacitor/cli

      - name: Clean up existing Android platform
        run: rm -rf android

      - name: Add Android platform
        run: npx cap add android

      - name: Sync project
        run: npx cap sync

      - name: Build Android App Bundle
        run: |
          cd android
          ./gradlew bundle

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/app-release.aab
